Change default nw port and improvements on docker-compose

diff --git a/extras/nw b/extras/nw
--- a/extras/nw
+++ b/extras/nw
@@ -1,16 +1,21 @@
 #!/bin/bash
 
-VAGRANT_PATH=/opt/nw-project
+NW_PATH=/opt/nw-project
+
+if [ `id -u` -ne 0 ]; then
+    echo "sudo is required"
+    exit 1
+fi
 
 case "$1" in
 up)
-    cd `echo $VAGRANT_PATH` && vagrant $1
+    VAGRANT_CWD=`echo $NW_PATH` vagrant $1
 ;;
 status)
-    cd `echo $VAGRANT_PATH` && vagrant $1
+    VAGRANT_CWD=`echo $NW_PATH` vagrant $1
 ;;
 destroy)
-    cd `echo $VAGRANT_PATH` && vagrant $1
+    VAGRANT_CWD=`echo $NW_PATH` vagrant $1
 ;;
 *)
     echo "Options: $0 {destroy|status|up}"
